[NUI] Window system
Changes:
```
using Tizen.NUI.WindowSystem;
Shell.TizenShell tzsh = new Shell.TizenShell();
```
produces compilation error: 
The type or namespace name 'Shell' could not be found (are you missing a using directive or an assembly reference?) [NUI_tzsh]csharp(CS0246)